### ISSUE TITLE
Sync custom tags back to server

### ISSUE THREAD

**Issue by thomasst** [inboxapp/inbox#130]
The current tags docs mention that Nilas doesn't sync changes to custom Gmail labels / IMAP folders back to the server because of "uniform interface across all providers". However, tags can be represented as labels on Gmail and as folders on IMAP accounts, therefore Nilas should add support for custom server-side tags.

**Comment by grinich** [comment]
It's a little bit more subtle than this. For example, what if a thread exists across multiple IMAP folders? When you add/remove a tag, what's the behavior? How can a developer know that adding a tag will remove all the other tags in this situation?

When we say "across all provider" we actually mean that. The example you game is Gmail, which is by far the most permissive and flexible. We can't support "custom server-side tags" because non-Gmail backends don't support tags.

**Comment by thomasst** [comment]
I've named both Gmail and generic IMAP accounts as an example. Adding a tag could just store another copy of the thread in the specific IMAP folder.

> How can a developer know that adding a tag will remove all the other tags in this situation?

It doesn't have to if you store a copy. But even if you decided to move the thread: How does a developer know now that adding the "archive" tag removes the "inbox" tag? You just have to be aware of the tagging behavior for specific tags / account types.
